### ISSUE TITLE
Dropdown api document has typo on type

### ISSUE THREAD

**Issue by YangFong** [qmhc/vexip-ui#109]
根据其他类型声明推断，此处应为 `boolean | string`，而不是分开的。没有找到站点文档文件，所以在此提一个 issue。

![image](https://user-images.githubusercontent.com/70502828/184529053-02476cca-03a1-498d-b17b-91cb19a02a15.png)

**Comment by qmhc** [comment]
Thx，发现了这么小了错误😂

**Comment by qmhc** [comment]
Fixed in https://github.com/qmhc/vexip-ui/commit/b8eae8cf16728d500f4a154d4f67f5ec51a55d58
