### ISSUE TITLE
icon spin 失效

### ISSUE THREAD

**Issue by YangFong** [qmhc/vexip-ui#112]
根据介绍，为 `<icon>` 添加 `spin` 属性可以使图标进行旋转状态，然而在浏览时发现，**文档中的例子都不会旋转**。

于是我进行了一波测试，发现 `spin` 属性仅限于 `:icon` 写法，无视插槽写法。

![动画](https://user-images.githubusercontent.com/70502828/185065877-755d7c29-2cb3-4b4b-9f4e-57f9712152f3.gif)

**Comment by YangFong** [comment]
补一个题外话，很多东西我都想尝试改动一下，但是不知道什么姿势来进行开发（环境测试），如果能有一份开发指导就好了。

![image](https://user-images.githubusercontent.com/70502828/185073894-93af09f9-50bd-4f07-91eb-5cbcb5264ad0.png)

**Comment by qmhc** [comment]
你可以先看看[贡献指南](https://github.com/qmhc/vexip-ui/blob/main/CONTRIBUTING.md)，开发的基本工作流是：针对某个组件开启开发服务，然后配合 `docs` 下对应组件的的 demos 目录来进行开发，如果是新组件可以用 `pnpm run create xxx` 来进行初始化。

需要帮助的话你也可以通过邮箱联系我~
