### ISSUE TITLE
`<Icon>` 设计

### ISSUE THREAD

**Issue by YangFong** [qmhc/vexip-ui#115]
找到了开发方式，于是我开始查阅源码，发现了 #112 产生的原因：少了 `<g>` 标签，而所有动画表现都绑定到了 `<g>` 标签上。

![image](https://user-images.githubusercontent.com/70502828/185297903-185dbad6-42c8-418d-a0df-b225877b6706.png)

这就很怪，因为 `<g>` 是属于 `<svg>` 当中的标签，我头一个想改的就是 `<Icon>`，想做的就是去除 `<g>` 标签。个人来看，动画可以绑定至外层 `<i>`，或者 `<svg>` 上，无需在此插入一个 `<g>`。

对此，想在此先询问一下建议，可行，我便对 `<Icon>` 进行整体重构。

**Comment by qmhc** [comment]
这个 `<g>` 标签是有意而为之的，为了让用户自定义的 transform 与内置的效果不发生冲突与覆盖的情况。

**Comment by qmhc** [comment]
你似乎一些想法和参与这个项目的意愿，如果是的话不妨通过我个人简介里的邮箱联系我或者加对应的某Q或者某V，我们可以做进一步的沟通。
