### ISSUE TITLE
Why the font-family is like this?

### ISSUE THREAD

**Issue by thetejasmagade** [qmhc/vexip-ui#118]
Why, you have used this font? or font is not showing/loading properly on my machine? see the image. Tell, me this so, I can fix it.
<br/>
![Screenshot 2022-08-20 120929](https://user-images.githubusercontent.com/53045273/185732604-58ed3e55-035d-4e67-98d4-a68dab28ec9d.jpg)

**Comment by qmhc** [comment]
Where is incorrect? I did not specify any `font-family` for normal content, it default is `Microsoft YaHei` when in Windows system. It will use your local font form your system.

**Comment by thetejasmagade** [comment]
I think You, Should have to change it from default to any other font. Because, it's not matching to website.

**Comment by qmhc** [comment]
What `font-family` do you think we should specify. We can discuss about it.

**Comment by thetejasmagade** [comment]
How's about ? Something, like Vue's website

**Comment by qmhc** [comment]
Are you mean the following?

![image](https://user-images.githubusercontent.com/40221744/185734733-1e3d6c9b-9374-43cf-ba62-b9650b67f45a.png)

It is worth trying. Do you want to contribute about this?

**Comment by thetejasmagade** [comment]
Sure, I will contribute. Thank you ❤️

**Comment by thetejasmagade** [comment]
Hey, @qmhc 
When I'm trying to commit my changes there is an error. Could, you please help me to resolve.
Thank you.
<br>
![Screenshot 2022-08-20 144106](https://user-images.githubusercontent.com/53045273/185738233-5d6c4057-2b91-4bb9-a7bc-fe9249e7e38d.jpg)

**Comment by qmhc** [comment]
@thetejasmagade You should use the Angular conventional commit message, the message will be verified before commit by `commitlint`.

Just like: `docs: improve font styling`

**Comment by thetejasmagade** [comment]
Thank You, Resolved

**Comment by thetejasmagade** [comment]
Hey @qmhc, 
I made the pull request
