### ISSUE TITLE
Error: Cannot find module 'consola'

### ISSUE THREAD

**Issue by zhang19980518** [qmhc/vexip-ui#135]
vite设置自动导入后  pnpm run dev报错Error: Cannot find module 'consola'

**Comment by zhang19980518** [comment]
failed to load config from /Users/zhang/Desktop/poio/vite.config.ts
error when starting dev server:
Error: Cannot find module 'consola'
Require stack:

**Comment by zhang19980518** [comment]
export default defineConfig({
  plugins: [
    vue(),
    createStyleImportPlugin({
      include: ['**/*.ts', '**/*.vue'],
      libs: [
        {
          libraryName: 'vexip-ui',
          esModule: true,
          base: 'vexip-ui/css/preset.css',
          resolveStyle: name => `vexip-ui/css/${name}.css`
        }
      ]
    })
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})

**Comment by qmhc** [comment]
这应该是 `vite-plugin-style-import` 依赖缺失的问题，你尝试一下手动安装 `consola`：

```sh
pnpm i -D consola
```

**Comment by zhang19980518** [comment]
解决了
