### ISSUE TITLE
引入图标报错

### ISSUE THREAD

**Issue by zhang19980518** [qmhc/vexip-ui#137]
引入图标后vite控制台报错
import { EnvelopesBulk, City, ChartPie, User, Marker } from "@vexip-ui/icons";

 Internal server error: Failed to resolve import "@vexip-ui/icons" from "src/views/AboutView.vue". Does the file exist?

**Comment by qmhc** [comment]
这是一个独立发布的图标库，是否已经安装了 `@vexip-ui/icons` ?

```sh
pnpm i @vexip-ui/icons
```

**Comment by zhang19980518** [comment]
解决了
