### ISSUE TITLE
Tabs 组件需求建议

### ISSUE THREAD

**Issue by vastlan** [qmhc/vexip-ui#2]
可将label作为导航页唯一索的属性用一个自定义属性来代替，这样可满足导航页的标题可以是文字（label）或者可以是符号（icon），解决了导航页标题仅为符号时点击无效的情况

**Comment by qmhc** [comment]
为 `TabPane` 添加了 `label` 插槽

> 仍需要 label 属性作为 Tabs 的唯一索引
