### ISSUE TITLE
不错的库，怎么没写单元测试

### ISSUE THREAD

**Issue by yzw2017** [qmhc/vexip-ui#26]
方便加个v交流一下吗

**Comment by qmhc** [comment]
你好，单元测试的编写已经列在工作清单上了，你可以检查[这里](https://github.com/qmhc/vexip-ui/blob/main/README.zh-CN.md#%E5%B7%A5%E4%BD%9C%E6%B8%85%E5%8D%95)。

目前东西都是我一个人写的，加上我还有主职工作，所以进度方面会稍微慢一些。😂

你可以留个邮箱，我们通过邮箱再交换 v，这里不太方便直接发 v 号。

**Comment by yzw2017** [comment]
778751745@qq.com @qmhc  技术交流 😄
