### ISSUE TITLE
[bug]: docs dark mode icon not right 

### ISSUE THREAD

**Issue by chris-zhu** [qmhc/vexip-ui#29]
发现一个小bug，文档中切换白天模式下的 Switcher icon 不正确，本来想提pr修复的，但是我 fork 后，运行不起来

步骤：
```sh
pnpm i
```
Then
```
pnpm run serve:docs
```

报错截图：
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/42139754/173185620-6192fea1-b15a-4abc-a770-ee439799912c.png">

请问我少了哪个步骤吗？

**Comment by qmhc** [comment]
你好，你需要把 `common` 下的 `utils`、`mixins` 和 `icons` 包都构建一次才可以在本地启动 `docs`。

![image](https://user-images.githubusercontent.com/40221744/173185701-3e6f8268-06e9-4ebb-aacb-76a59480be8f.png)

你可以用这条命令一次性构建 `common`。
