### ISSUE TITLE
【Collapse】点击第一个示例后，当前页面会卡死

### ISSUE THREAD

**Issue by leno23** [qmhc/vexip-ui#50]
bug位置：【在线文档】【中文】【组件】【Collapse】
复现条件：点击第一个示例后，当前页面会卡死
截图：![image](https://user-images.githubusercontent.com/39647285/174518282-5be906cc-b2f3-434e-b4d5-b933c83c7dce.png)

**Comment by leno23** [comment]
可以让我尝试修改下么？😆

**Comment by qmhc** [comment]
非常欢迎，你可以参考 [贡献指南](https://github.com/qmhc/vexip-ui/blob/main/CONTRIBUTING.md) 来开发。

**Comment by qmhc** [comment]
你可以重点关注一下 `Collapse` 组件中，在 `watch` 中进行了派发双向绑定的事件 `emit('update:expanded')` 的行为，我认为问题主要出现在那里，改为手动控制事件的派发应该能够解决这个问题。

**Comment by qmhc** [comment]
你可以重点关注一下 Collapse 组件中，在 watch 回调进行了派发双向绑定事件 emit('update:expanded') 的行为，我认为问题主要出现在那里。

**Comment by leno23** [comment]
> 你可以重点关注一下 Collapse 组件中，在 watch 回调进行了派发双向绑定事件 emit('update:expanded') 的行为，我认为问题主要出现在那里。

好的  我去定位下

**Comment by leno23** [comment]
> 你可以重点关注一下 Collapse 组件中，在 watch 回调进行了派发双向绑定事件 emit('update:expanded') 的行为，我认为问题主要出现在那里。

昨天看了下，本地环境没有复现🤣

**Comment by leno23** [comment]
> @leno23 本地环境是有的，示例的顺序已经调整了，手风琴的示例不在第一位。
> 
> 在开发环境下 vue 的栈溢出会抛出一个警告，不会卡死，你可以检查警告信息。

哦哦   这样子，我去看下

**Comment by leno23** [comment]
> @leno23 本地环境是有的，示例的顺序已经调整了，手风琴的示例不在第一位。
> 
> 在开发环境下 vue 的栈溢出会抛出一个警告，不会卡死，你可以检查警告信息。

g

**Comment by leno23** [comment]
@qmhc  Collapse的expanded属性优先级要高度CollapsePane的吧？

**Comment by leno23** [comment]
> Collapse 会往下注入（`provide`）一个 [`COLLAPSE_STATE`](https://github.com/qmhc/vexip-ui/blob/c6c3112f65a6e245296ff3ba6eadd98274dfa80d/components/collapse/collapse.vue#L68)，CollapsePane 在初始化时如果能接收（`inject`）到这个状态，将会放弃观察（`watch`）自身的 `expanded` 属性，并将内部的 `currentExpanded` [注册到](https://github.com/qmhc/vexip-ui/blob/c6c3112f65a6e245296ff3ba6eadd98274dfa80d/components/collapse/collapse-pane.vue#L123) Collapse 提供的 `state` 上，由 Collapse 来控制该属性的更新。
> 
> 你关闭这个 issue 是误操作了吗？

是的  刚刚估计点错了🤣

**Comment by leno23** [comment]
@qmhc   逻辑有点绕，我再看看。
我这里还发现一个问题是是 Collapse组件的expanded属性 并没有被CollapsePane接收，导致现在的Collapse组件的expanded属性设置不生效🤣

**Comment by qmhc** [comment]
@leno23 你好呀，最近是否有进展？

**Comment by leno23** [comment]
> @leno23 你好呀，最近是否有进展？

前两天工作有点忙，今天我再看看

**Comment by leno23** [comment]
@qmhc 
你好，这个问题的原因找到了，但是我不知道应该如何修改😂。
原因是在currentExpanded的watch回调中会提交expanded的双向绑定事件，从而引发props.expanded的改变。这样就会触发watchEffect中副作用函数的执行，再次修改了currentExpanded，然后重新触发watch回调...   造成了死循环

**Comment by leno23** [comment]
> @qmhc 能否请教一下解决这个问题的思路？

**Comment by qmhc** [comment]
@leno23 你可以尝试将 `currentExpanded` 的 `watch` 移除掉，并将事件的派发直接放在触发了 `currentExpanded` 变化的方法中。

在 Collapse 目前只有 `expandPane` 这个一个方法会修改 `currentExpanded`，可以在这个方法的最后放事件的派发的代码。

**Comment by leno23** [comment]
> @leno23 你可以尝试将 `currentExpanded` 的 `watch` 移除掉，并将事件的派发直接放在触发了 `currentExpanded` 变化的方法中。
> 
> 在 Collapse 目前只有 `expandPane` 这个一个方法会修改 `currentExpanded`，可以在这个方法的最后放事件的派发的代码。

好的  我按照这个思路尝试修改下

**Comment by qmhc** [comment]
你好，这个问题最近有进展吗？我想尽快修复这个问题。
