### ISSUE TITLE
文档中左边的 Notice 被菜单遮挡

### ISSUE THREAD

**Issue by ccakee** [qmhc/vexip-ui#57]
可否考虑为组建添加z-index层级 ， 文档中打开时 ，左下角和左上角弹出会被菜单遮住

**Comment by qmhc** [comment]
在存在一些自定义的 `z-index` 的时候，确实会不可避免的出现，因为现在组件内的 `z-index` 是固定值。

近期计划在顶层添加一个动态调度 `z-index` 的 mixin (hook) 来解决这个问题。

**Comment by qmhc** [comment]
这个是当前文档样式的一个 bug，我先将这个 issue 用于跟踪该问题，新增顶层调度 `z-index` 将重新打开一个 issue 跟踪。

**Comment by qmhc** [comment]
文档中的该问题在 beta.12 版文档中已修复，先关闭该 issue。
