### ISSUE TITLE
Zooming bug in component Viewer, by mouse wheeling and zoom button.

### ISSUE THREAD

**Issue by orangelckc** [qmhc/vexip-ui#66]
A bug occurs in component Viewer, the picture is flipped when scaling down, and if you continually to shrink it, the picture will become bigger instead.

BUG位置：在Viewer组件中缩放图片，会出现图片的翻转，当继续缩小，图片反而会变大。

> 通过直播知道了这个组件库，希望能够参与其中的一些开源工作，向作者大佬学习。

**Comment by qmhc** [comment]
在开始的设计上是故意留了这个口子让图片缩放到最小后可以翻转过来了。

不过这样可能在使用上不符合第一直觉，我觉得可以增加一个属性来控制这一行为，你有兴趣尝试吗？

如果想参与，可以随时在 issue 列表中寻找自己感兴趣的内容并回复沟通~

**Comment by orangelckc** [comment]
> 在开始的设计上是故意留了这个口子让图片缩放到最小后可以翻转过来了。
> 
> 不过这样可能在使用上不符合第一直觉，我觉得可以增加一个属性来控制这一行为，你有兴趣尝试吗？
> 
> 如果想参与，可以随时在 issue 列表中寻找自己感兴趣的内容并回复沟通~

刚才看了Viewer的源码，应该是当zoom值减小到负数后就会翻转，可以给zoom一个最小值，在emit之前进行判断。
对于翻转，倒是可以添加一个镜像的功能，就是左右翻转。
不知道是否符合设计的初衷，我也很乐意参与到项目中。

**Comment by qmhc** [comment]
我觉得可以添加 `min-zoom` 和 `max-zoom` 这样的属性来支持可定制化的缩放。

可以添加一个镜像翻转的操作，当初由于组件着急上线，所以使用场合相对较少的翻转功能被拿掉了。

你随时都可以开始~

如果你还想要开发翻转功能，可以再打开一个新的 issue，并且用一个和这个问题不同的分支来开发，这样能保证 PR 的独立。
