### ISSUE TITLE
【Table】表格固定列横向滚动bug

### ISSUE THREAD

**Issue by ivan0525** [qmhc/vexip-ui#82]
复现条件：文档“固定行列”示例，使用mac妙控板无法横向滚动，只能实现纵向滚动。横向需拖拽滚动条。

**Comment by qmhc** [comment]
Table 的滚动并不是一个自由滚动，它的纵向和横向滚动是作用在不同元素上的。

在用鼠标交互时，直接的滚动是纵向，按住 Shift 后滚动则为横向。

mac 妙控板是否可以像鼠标一样配合键盘的 Shift（或类似的指令，我不太了解）一起使用？

**Comment by qmhc** [comment]
长时间未回复，暂时关闭 issue。
