### ISSUE TITLE
Failed to fetch dynamically imported module: http://127.0.0.1:8008/app.vue

### ISSUE THREAD

**Issue by claviering** [qmhc/vexip-ui#89]
after `pnpm install`、`pnpm run build:common` and  `pnpm run serve` then open in the browser

<img width="897" alt="image" src="https://user-images.githubusercontent.com/16227832/179146892-95ba953d-6e4f-481c-ad7d-4d9711f2066b.png">

**Comment by qmhc** [comment]
Could you provide the output of `npx envinfo --system --binaries --browsers`?

**Comment by claviering** [comment]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/16227832/179151864-fd1b47ba-ae00-46b7-9eb1-18153fd2d2df.png">

**Comment by qmhc** [comment]
`pnpm i`, `pnpm run build:common`, `pnpm run serve alert`

I tested in Ubuntu20 and macOS11, but cannot reproduce it...

**Comment by qmhc** [comment]
I reproduce it on Windows😂

**Comment by qmhc** [comment]
This is caused by AD block plugin of browser, because this icon path ends with `ads.mjs`.

It is very strange for the blocking rules of this plugin.

**Comment by claviering** [comment]
oh!
